<?xml version="1.0"?>
<package format="3">

  <name>intra_process_demo</name>

  <version>0.0.1</version>

  <description>
    ROS2 intra-process communication and composition demonstration.
  </description>

  <maintainer email="yehiaelkh@gmail.com">
    Yehia Elkh
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rclcpp_components>
      <node plugin="intra_process_demo.xml"/>
    </rclcpp_components>
  </export>

</package>