<?xml version="1.0"?>

<package format="3">

  <name>thread_safety_demo</name>

  <version>0.0.1</version>

  <description>
    ROS2 demonstration of advanced C++ concurrency,
    thread safety, mutexes, atomics and race conditions.
  </description>

  <maintainer email="yehiaelkh@gmail.com">Yehia Elkh</maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
